# Generated by Django 5.2.4 on 2025-08-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='specialites/')),
                ('categorie', models.CharField(choices=[('entrée', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
